### ISSUE TITLE
IronList loads all items at once from backend

### ISSUE THREAD

**Issue by heruan** [vaadin/vaadin-iron-list-flow#54] opened 2018-08-08 14:15 UTC
The `Query` passed to the data provider by `IronList` has always offset 0 and limit the total number of items.

**Comment by heruan** [comment] 2018-08-08 15:10
Sample project: https://github.com/heruan/flow-test/tree/iron-list-lazy

**Comment by Legioth** [comment] 2018-08-08 16:28
It seems like things work nicely if using "regular" content, as can be seen e.g. with the `createStringListWithDataProvider()` example in https://github.com/vaadin/vaadin-iron-list-flow/blob/master/src/test/java/com/vaadin/flow/component/ironlist/demo/IronListView.java.

The problem is that when using a component renderer, the content for each item is initially rendered with 0px height because of the way the actual components are attached lazily. This makes `<iron-list>` keep adding more and more items to the DOM to in order to fill up all the available height.

As a workaround, it might work to use CSS to set a minimum height for `iron-list > flow-component-renderer` according to the size of the items for any particular list.

**Comment by Legioth** [comment] 2018-08-08 16:38
The particular example in the sample project can also be fixed by using the default renderer instead of `TextRenderer` (yes, it's slightly confusing that `TextRenderer` is completely different compared to the default renderer).

Line 43 in `IronListLazy.java` could thus be changed to `this.list.setRenderer(Person::getFullName);`

**Comment by Legioth** [comment] 2018-08-08 16:54
Probably related to #26 and #27

**Comment by heruan** [comment] 2018-08-09 05:30
Thank you @Legioth for the analysis, I understand this now. Basically, with a component renderer the `<template>` element is empty at first and don’t occupy any space, so the list considers all the items could be rendered at the same time.

I’ll test your suggestions with CSS height, but why not use a CSS variable for the height of `flow-component-renderer` such as `--flow-component-renderer-height` with a reasonable default which can be overridden on the list by the developer to fine tune the performance? In the worst case (variable not overridden and items much taller than the default height) the list will request a larger number of items than needed, which is better than all the items.

**Comment by Legioth** [comment] 2018-08-09 07:45
The point of my suggested workaround is that it should (hopefully) work already today.

It's then a good question what we should change or introduce to properly fix this. Some alternatives:
* Allow defining a default height using a CSS variable
* Allow defining a default height from Java
* Make the placeholder item concept work (transparently) also for component renderers (#26)
* Somehow get rid of the asynchronous attach of the actual components (though this would still not work for lazy loading).

**Comment by heruan** [comment] 2018-08-09 19:49
@Legioth At first your workaround seemed to work, but actually it works just the first time the component is loaded. In detail:

- Load directly the route target with the list: requested range 0 to ~50 (good)
- Load another route target, then navigate in-app to the list: requested range 0 to ~50 (good)
- Navigate in-app away from the list, then come back: requested range 0 to ~10.000 (BAD)

What may be causing such a behavior?

**Comment by Legioth** [comment] 2018-08-10 05:59
I cannot reproduce the behaviour you're describing. It sounds like the style would for some reason not be applied when navigating back, maybe because of a timing issue or because something causes the DOM structure to be slightly different?

To help debug this, you might want to put a JS breakpoint in the `updateRequestedItem` function in `ironListConnector.js` so that you can check what styles are applied to the `<flow-component-renderer>` elements that the moment when the number of items to fetch is calculated.

**Comment by heruan** [comment] 2018-08-10 06:19
I cannot replicate either in my sample project, but it happens in another one with the same versions. Maybe as you said it's a timing issue, since that project has a more complex structure to load, but I checked the style during debug and it is already applied when the update function is called (in fact the style is imported by the main layout).

**Closed** 2018-08-29 08:26 UTC
Labels: bug, components
